// Re-export everything from the shared package so existing client imports work unchanged.
export {
  GLOBAL_COOLDOWN,
  YARDS_TO_UNITS,
  yardsToUnits,
  CoveredInPiss,
  BucketSplash,
  Mop,
  DebugStun,
  BigBootStun,
  BigBoot,
  FartBombDebuff,
  FartBomb,
  CrashOutBuff,
  CrashOut,
  Sweep,
  BottleChuck,
  DiscombobulateDebuff,
  Discombobulate,
  ChemicalSpillSpeedBuff,
  ChemicalSpillDot,
  ChemicalSpill,
  RetardStrengthBuff,
  RetardStrength,
  Chudmax,
  FullRetardBuff,
  FullRetard,
  CrotchRotDot,
  RottenCrotchStun,
  CrotchRot,
  JimmyLegsDebuff,
  JimmyLegdDebuff,
  JimmyLegs,
  KaboomStun,
  Kaboom,
  Shank,
  CrackRockSpeedBuff,
  CrackRock,
  TweakerSprintSlow,
  TweakerSprint,
  ArenaPreparationBuff,
  RestingBuff,
  PvPTrinket,
} from '@gtr/shared';

export type { Ability, BuffDefinition, BuffEffect } from '@gtr/shared';
